# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popiszivali',
            name='kvadrant',
            field=models.CharField(max_length=10),
        ),
    ]
