# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170520_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popiszivali',
            name='vrsta',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
