# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_popiszivali_avtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popiszivali',
            name='ogrozenost',
            field=models.CharField(max_length=2),
        ),
    ]
