# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170521_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popiszivali',
            name='biolog',
            field=models.CharField(max_length=50),
        ),
    ]
